name: Lighthouse Report
on: [push, workflow_dispatch]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Audit site with Lighthouse
        # Usamos la acción oficial de Google Chrome
        uses: foo-software/lighthouse-check-action@master
        with:
          # Al ser un HTML estático, le decimos que mire el archivo local
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          urls: 'https://candradehuetio.github.io/proyecto2-pages/'
