name: HTML Linter
on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: HTML Check
        # Usaremos esta versión que es más estable y reconocida
        uses: ammar-at/html-linter-action@v2
        with:
          source: "." # Esto revisará todos los archivos .html en tu raíz
